# Generated by Django 5.2.4 on 2025-08-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_academicterm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AcademicTerm',
        ),
        migrations.DeleteModel(
            name='SessionYearModel',
        ),
    ]
